# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool: MsGraphDevXAzureAgents

variables:
  BranchName: 'test_weeklyOpenApiDocsDownload'
  BranchDate: "$[format('{0:yyyyMMdd}', pipeline.startTime)]"
  BaseBranch: 'dev'
  AUTH_MODULE_NAME: 'Authentication'
  AUTH_MODULE_PATH: 'src\Authentication\Authentication'
  AUTH_MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
  MODULE_DLL_PATTERN: 'Microsoft.Graph.Authentication.dll'
  MODULE_PREFIX: 'Microsoft.Graph'
  ROLLUP_MODULE_NAME: 'Graph'
  ROLLUP_MODULE_PATH: 'src/Graph/Graph'
  WORKLOAD_MODULE_PATH: 'src'
  Api_Key: 'Api_Key'
  EnableSigning: true
  BUILDNUMBER: -1

schedules:
- cron: "0 12 * * WED" # Run every wednesday at noon UTC
  displayName: "Weekly SDK Generation"
  branches: 
    include:
    - dev
  always: true

stages:
  # Run checkout stage.
  - stage: DownloadOpenAPIDocs
    displayName: 'Download OpenAPI Docs'
    jobs:
    - template: common-templates/download-openapi-docs-stage.yml
      parameters:
        Branch: $(BranchName)
        BaseBranch: $(BaseBranch)

  - stage: GenerateModulesWithChanges
    displayName: Generate module with changes
    jobs:
      - job: GenerateModules
        displayName: Generate modules with changes
        condition: and(succeeded(), ne(stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['OpenAPIDocDiff.ModulesWithChanges'], ''))
        variables:
          ModulesWithChanges: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['OpenAPIDocDiff.ModulesWithChanges'] ]
        steps:
          - task: PowerShell@2
            displayName: Generate module
            inputs:
              pwsh: true
              targetType: inline
              script: |
                Write-Host $(BranchName)
                Write-Host $(BranchDate)
                Write-Host $(BaseBranch)
                Write-Host "Generating changed modules...."
                "$(ModulesWithChanges)" -split " " | %{
                  Write-Host $_
                }

  - stage: GenerateServiceModules
    displayName: Generate Service Modules
    variables:
      ModulesToGenerate: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['OpenAPIDocDiff.ModulesWithChanges'] ]
    jobs:
      - template: generation-templates/generate-service-modules.yml
        parameters:
          ModulesWithChanges: $(ModulesToGenerate)
          Api_Key: $(Api_Key)
          MODULE_PREFIX: $(MODULE_PREFIX)
          WORKLOAD_MODULE_PATH: $(WORKLOAD_MODULE_PATH)
          AUTH_MODULE_PATH: $(AUTH_MODULE_PATH)
          AUTH_MODULE_DLL_PATTERN: $(AUTH_MODULE_DLL_PATTERN)
          EnableSigning: true
          BUILDNUMBER: $(BUILDNUMBER)


  # Git diff on download OpenAPI docs. Store changed modules in a variable.
  # Commit downloaded docs.
  # If modules change, bump their minor and meta-module version.
  # Generate changed modules + run tests.
  # Commit generated files to weekly branch.
  # Create PR to dev