# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pool: MsGraphDevXAzureAgents

variables:
  BranchDate: "$[format('{0:yyyyMMddHHmm}', pipeline.startTime)]"
  Branch: "testweeklyOpenApiDocsDownload/$(BranchDate)"
  BaseBranch: "dev"
trigger: none
pr: none
schedules:
  # - cron: "0 12 * * WED" # Run every wednesday at noon UTC
  - cron: "40 0 * * *" # Test runs
    displayName: "Weekly PS SDK generation"
    branches:
      include:
        - dev
        - po/*
    always: true

stages:
  - stage: DownloadOpenAPIDocs
    displayName: Download OpenAPI docs
    jobs:
      - template: common-templates/download-openapi-docs.yml
        parameters:
          Branch: $(Branch)
          BaseBranch: $(BaseBranch)

  - stage: GenerateServiceModules
    displayName: Generate service modules
    variables:
      ModulesToGenerate: $[ stageDependencies.DownloadOpenAPIDocs.GetLatestDocs.outputs['OpenAPIDocDiff.ModulesWithChanges'] ]
      AuthModulePath: "src/Authentication/Authentication/bin/"
      AuthModuleDllPattern: "Microsoft.Graph.Authentication.dll"
      ServiceModulePath: "src/"
      ModulePrefix: "Microsoft.Graph"
    jobs:
      - template: generation-templates/generate-service-modules.yml
        parameters:
          # Branch: $(Branch)
          # AuthModulePath: $(AuthModulePath)
          # AuthModuleDllPattern: $(AuthModuleDllPattern)
          # ServiceModulePath: $(ServiceModulePath)
          # ModulePrefix: $(ModulePrefix)
          EnableSigning: true
          PublishToFeed: false
  # Git diff on download OpenAPI docs. Store changed modules in a variable.
  # Commit downloaded docs.
  # If modules change, bump their minor and meta-module version.
  # Generate changed modules + run tests.
  # Commit generated files to weekly branch.
  # Create PR to dev
